### ISSUE TITLE
Initial rendering seems to hang

### ISSUE THREAD

**Issue by sophiekoonin** [tweetback/tweetback#30]
Hey folks! I left my build running for two hours and realised it'd only got a little way through my tweets (judging by the number of images it'd saved). With no verbose console output I couldn't tell it wasn't doing anything.

I added a console.log in `twitter.js:295` and now I can see that after a short while the build hangs. If I cmd+c the build and run it again, it runs through the already-built tweets very quickly and picks up where it left off, building but then hanging again later, so I have to repeat the process. With 20k+ tweets this is taking a long time 😓 

What's the best way of debugging what's going on here?

**Comment by zachleat** [comment]
it’s remotely fetching high quality images from the CDN using Eleventy Image https://www.11ty.dev/docs/plugins/image/ and caching the http request responses into your `.cache` folder. The image content is then also saved into a `git`-able folder so that they will not be requested again.

This is noted on the README but I do think it probably isn’t obvious enough https://github.com/tweetback/tweetback#build-the-web-site

**Comment by zachleat** [comment]
We could make this better with #35

**Comment by zachleat** [comment]
Please follow along at #35!
